# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda_arm_controller
    - hand_controller

  panda_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Shoulder Roll
      - Shoulder Pitch
      - Elbow Pitch
      - Elbow Roll
      - Wrist Pitch
      - Wrist Roll
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - Wrist Roll
    action_ns: gripper_cmd
    default: true